### ISSUE TITLE
Graphical oddity: Shadow looks like it is only part strength for most of the window (all but some at the top)

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/emerald#12]
Screenshot: 
![screenshot_2016 07 03_01 42 33](https://cloud.githubusercontent.com/assets/10457522/17199886/65eb96a6-544e-11e6-876d-b20cf1425020.png)

**Comment by soreau** [comment]
What theme/engine does this happen with? It seems to work as expected with TiSkin_Classic at least.

**Comment by ethus3h** [comment]
@soreau: Theme is attached; engine is oxygen.


[Wreathe 7r3, 2016jul02n2 exported 2016jul30.emerald.txt](https://github.com/compiz-reloaded/emerald/files/392111/Wreathe.7r3.2016jul02n2.exported.2016jul30.emerald.txt)

**Comment by ethus3h** [comment]
This issue is still happening for a number of themes, for example the bundled themes Overglossed, Mac4Lin_Graphite, Fogo_Monochrome, and the one I linked in the GitHub issue. Was it intentionally closed?

**Comment by soreau** [comment]
Sorry, I thought we had determined this was a non-issue on IRC.

**Comment by ethus3h** [comment]
No worries :) (We talked about it, but I don't remember there being any resolution…)

**Comment by zezic** [comment]
I found some things directly related to this problem:
1) Generated gaussian kernel wrong http://i.imgur.com/s8Lcecv.png (lolled at this shape all day)
2) Wrong use of transform matrix coordinates around this place https://github.com/compiz-reloaded/emerald/blob/master/src/main.c#L882-L956 which produces bottom part placed at area which should be stretched over left and right shadow parts.
