### ISSUE TITLE
Emerald crashes

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/emerald#13]
Here is the terminal output from a crash: https://gist.github.com/ethus3h/74cdf58340955be4c174bf3948604b35

There are a couple compiz crash logs in /tmp, dated last night, but no emerald ones.

**Comment by ethus3h** [comment]
Another one: https://gist.github.com/ethus3h/029880185aca23fedcef420a438212c9

**Comment by ethus3h** [comment]
Confirmed to happen with Blue_Planet oxygen-engine theme; trying with Blue_Submarine (vrunner) now.

**Comment by ethus3h** [comment]
Confirmed to happen with Blue_Submarine vrunner theme; log available: https://gist.github.com/ethus3h/6402f9440a17d4dd0892bb0cc8a164f7

**Comment by ethus3h** [comment]
I can reliably reproduce this by opening HexChat when it was not already running, while Emerald is running. Backtraces for the crash: https://gist.github.com/ethus3h/0899ab74ea5f9bd2648494d7ec8501e0

**Comment by soreau** [comment]
I cannot reproduce this problem. Which emerald theme are you using?

**Comment by ethus3h** [comment]
Hexchat crash confirmed to happen with Blue_Submarine vrunner theme.

**Comment by soreau** [comment]
It still doesn't happen here, even with that theme. Can you rebuild with CFLAGS='-O0' and get another trace?

**Comment by ethus3h** [comment]
This issue seems to be unrelated to the theme, but it does not affect gtk-window-decorator. It occurs when the following conditions are true, as far as I can tell:
* A non-monochrome typeface is installed (in my case, [Noto Color Emoji](https://noto-website.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip)).
* Window title contains a character for which the non-monochrome typeface is being used (in my case, a character for which only Noto Color Emoji contains a glyph).

**Comment by ethus3h** [comment]
It *did* affect gtk-window-decorator! I tested it before and thought it didn't, but it did this time. It did not affect Openbox (rather, the titlebar contained a replacement character instead of the emoji).

The version of GTK (2 vs 3) does not seem to affect it.

**Comment by ethus3h** [comment]
Information known so far:

The issue is:

* Emerald crashes with the message `emerald: /var/tmp/portage/x11-libs/cairo-1.14.6/work/cairo-1.14.6/src/cairo-scaled-font.c:459: _cairo_scaled_glyph_
page_destroy: Assertion `!scaled_font->cache_frozen' failed.`

* gtk-window-decorator crashes with the message `gtk-window-decorator: /var/tmp/portage/x11-libs/cairo-1.14.6/work/cairo-1.14.6/src/cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.`.

The issue is not related to the selected Emerald theme.

The issue occurs both when Emerald is built with GTK2 and when it is built with GTK3.

The issue occurs with both pango-1.38.1 and 1.40.1.

The issue occurs with both en_GB.utf8 and en_US.utf8 locales (with a reboot after changing the locale).

The issue occurs when Noto Color Emoji is used for a character in a window title.

The issue does not affect Openbox (which does not seem to use Noto Color Emoji in window decorations at all, even for characters for which only it contains glyphs).

gtk-window-decorator works if there is a window title with a problem emoji in it (in any position) at the time when gtk-window-decorator is started.

However, if there is not a problem emoji in the title when it is started, it will crash when a window title is set to a string containing a problem emoji (in any position).

Emerald does not work if there is a window title with a problem emoji in it, crashing immediately if there is a problem emoji in a window title when it is started.

The position (start, middle, end) does not seem to affect the behaviour of either gtk-window-decorator or Emerald.

**Comment by ethus3h** [comment]
Should be fixed for Emerald by https://github.com/compiz-reloaded/emerald/commit/7f712c5f4fb2dbc8bbe298acc8fef239815aea08 — thanks @herbertp and @XRevan86 ! :)
