### ISSUE TITLE
emerald 8.14 exec issue in debian sid

### ISSUE THREAD

**Issue by H2L29** [compiz-reloaded/emerald#24]
Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by XRevan86** [comment]
Maybe Emerald's libraries are built with Gtk2 (libemeraldengine.so) and Emerald itself – with Gtk3.

**Comment by XRevan86** [comment]
Which means you probably have Emerald built with different GTK+ installed somewhere, libraries of which take priority.
