### ISSUE TITLE
Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/emerald#25]
This crash is reliably reproducible when running the non-libre program "KuaiZip" in WINE.

Backtrace: https://gist.github.com/ethus3h/7f27b9ab9b29ceac97fc7e98f80d13c0

**Comment by ethus3h** [comment]
This happens with Notepad++ in WINE, too.

It occurs both with and without GTK+ 3 theming support enabled in WINE.

**Comment by soreau** [comment]
I can't reproduce with cairo 1.14.6 and notepad++ here
