### ISSUE TITLE
Feature request: Give ability to disable window shading feature, or set notable visual effect to the title bar of shaded window.

### ISSUE THREAD

**Issue by moontide** [compiz-reloaded/emerald#4]
I'd like to disable the 'shade' feature in emerald. I don't use it.

I can hide the shade button via emerald-theme-manager, but this feature is not disabled, and could be triggered by mistake.

**A common mistaken operation**
On touchpad, use double fingers to scroll up (web pages for example), and when the cursor is closed to title bar, cursor can often moved to title bar (that's not touchpad's fault, but fingers'), and triggered shade

**A confusing result after a mistaken operation**
Visually, I will saw a title bar of shaded window + body of another window, such as a "FirefoxCaja" window.

**Comment by zezic** [comment]
OK! It's easy to implement. I do that soon.

**Comment by moontide** [comment]
Thanks a lot!
I can now disable window shading in [`emerald-0.8.12.2-1.fc23`](http://koji.fedoraproject.org/koji/buildinfo?buildID=745850).
