### ISSUE TITLE
Glow (Halo) Effect Glitch

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [compiz-reloaded/emerald#5]
In the new version of Emerald the glow (halo) effect glitches and appears strangely. I am seeing this on a dark Windows Aero style theme which can be exported and sent if needed to help fix this.
![screenshot 2016-03-26 20 53 51](https://cloud.githubusercontent.com/assets/7698035/14062384/e28f5e74-f394-11e5-8918-52fba246adec.png)

**Comment by soreau** [comment]
You say this happens in the new version. Was there a version were it worked previously?

**Comment by KUPOinyourWINDOW** [comment]
Yep, the version of 0.8.12 that I used pretty much as soon as you turned it on (I was having trouble installing 8.10 and you helped me out in the comments).

**Comment by soreau** [comment]
If there is a good git hash where it works, then a git bisect can help to find the first bad commit and figure out what's going on. If you don't know how or don't want to do that, maybe tinkering with the theme settings will help.

**Comment by KUPOinyourWINDOW** [comment]
I don't know how to do that, I'll try ZIP up the theme and attach it here.

**Comment by XRevan86** [comment]
@KUPOinyourWINDOW, no, no need for that. There are themes in emerald-themes that have the problem.

**Comment by soreau** [comment]
I bisected and found af882eac is the first bad commit causing the problem, "Support Super Maximize button (fullscreen)". This means you should be able to use 075e36f5. Run 'git clone https://github.com/compiz-reloaded/emerald && cd emerald && git checkout 075e36f5 && ./autogen.sh ...' replacing the ellipsis with the rest of the build command. Thanks for reporting this.
