### ISSUE TITLE
Scrollbar Not at Edge of Screen

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [compiz-reloaded/emerald#7]
I'm unsure of if this is a Compiz or an Emerald behaviour but I see that Emerald has a decoration cropping feature that changes the position of the scrollbar with different decorations.

The problem is that it becomes irritating to scroll down pages precisely when the scrollbar isn't at the very edge of the screen. As it is now I have to move my mouse to the edge of the screen and then left a bit before I can grab the scrollbar. 

If this is something that could be fixed it would be much appreciated!

**Comment by XRevan86** [comment]
With decoration cropping enabled maximised windows should have scrollbar at the very end regardless of the theme…

**Comment by KUPOinyourWINDOW** [comment]
This is not the case for me on a 1280x800 screen. The scrollbar does appear at the edge but it's not quite there as you can't move your mouse to the edge of the screen to click and drag the scrollbar. It's off slightly.

**Comment by soreau** [comment]
I'm not sure if this is the problem, but does it still happen if you disable wall and cube? I'm thinking the settings in wall>bindings>edge flipping or rotate>bindings>rotate cube>rotate flip* might be interfering.

**Comment by KUPOinyourWINDOW** [comment]
It doesn't happen with those disabled! You're right! I only use the cube so in my case it was "rotate flip" that was interfering, as soon as I removed "right" and "left" edge bindings the scrollbar works perfectly.
