### ISSUE TITLE
after recent update of some Compiz-Reloaded packages Emerald no longer loads

### ISSUE THREAD

**Issue by fraterchaos** [compiz-reloaded/emerald#8]
Yesterday I ran some updates from the AUR (I'm running Manjaro Linux) and it updated some of the Compiz-Reloaded packages, and when I rebooted today, Emerald would not start, and I can't get my borders when I select them in the Emerald Editor, nor can I run emerald --replace in terminal (I get a Segmentation Fault (core dumped) error)

It is also interpreting my shift-a and shift-d keys as window border toggles when using GTK decorations in place of the missing Emerald ones... (I can only type a capital a or d using Caps Lock, using shift only toggles the GTK border on and off)

I do not believe the updates actually updated Emerald-git, but it did update some of the Compiz-Reloaded packages, Compiz-core and all the plug-in packs I think, and the XFCE Panel patch for Compiz.

Thanks

EDIT: ok, after switching back and forth between GTK and Emerald a few times, the emerald theme suddenly started to work again, no idea why. Still having the issue with the shift-a and shift-d keys acting as border toggles instead of being normal typed characters though

EDIT2: ok, the issue with the keyboard was my own stupid fault. When Emerald first refused to load I checked "Toggle Decorations" in the Compiz settings... not sure if Emerald is still going to load or not on my next boot up, but if not, at least I have a work around...

**Comment by ShadowKyogre** [comment]
Hey there @fraterchaos. Packager for the AUR here. When Emerald was segfaulting, did you try rebuilding it after the rest of the compiz-reloaded packages compiled?

I ask this since I know that the plugin packs can segfault if they're built against a different compiz version (which might be the old one). That might've been what happened with emerald.

**Comment by fraterchaos** [comment]
well, at first I didn't, but later one I decided to try reinstalling it, and then it was sometime after that that it seemed to work again, so you're probably right.

So far it seems to be working correctly again, not sure if it will use my borders next time I boot or not, but I'm guessing it will.

**Comment by ShadowKyogre** [comment]
Understood! Let me know if any other issues come up.

**Comment by fraterchaos** [comment]
will do. If I don't post on this issue again, you can assume it is working when I reboot.

and thanks for all your hard work on this... I love Compiz-Reloaded

if you've not seen it, here's my current desktop:

https://www.youtube.com/watch?v=ypBe1HoVql0

(I'm the one Spatry mentioned with the Tardis desktop)

**Comment by XRevan86** [comment]
Compiz 0.8.14 will have a different libdecoration API so Emerald has to be rebuilt against it.
