### ISSUE TITLE
buttons in pixmap engine settings are to huge

### ISSUE THREAD

**Issue by raveit65** [compiz-reloaded/emerald#9]
This happens with all gtk+3 themes with emerald gtk3.
![bildschirmfoto zu 2016-05-19 12-10-03](https://cloud.githubusercontent.com/assets/961604/15390235/26bddad0-1dbb-11e6-8230-47c3abf45aef.png)

**Comment by XRevan86** [comment]
It was the case for a long while, including Gtk2 builds. Trick is that the box expands vertically because of the image.

**Comment by raveit65** [comment]
You mean the image inside the button or the graphic between filechooserbutton and empty button?

**Comment by XRevan86** [comment]
The graphic between. I guess we have to make buttons unexpandable :-).
